### ISSUE TITLE
Release 1.13 causes RemoteWebdriver Wait Until error (RemoteWebDriver.php:581)

### ISSUE THREAD

**Issue by gwillyoo** [php-webdriver/php-webdriver#1022]
### Bug description
Make webdriver wait until expected condition. But suddenly shows error. Here is the stack.

```php
vendor/php-webdriver/webdriver/lib/WebDriverWait.php(54): call_user_func()

[internal function]: Facebook\WebDriver\WebDriverExpectedCondition::Facebook\WebDriver\{closure}()

vendor/php-webdriver/webdriver/lib/WebDriverExpectedCondition.php(178): Facebook\WebDriver\Remote\RemoteWebElement->isDisplayed()

vendor/php-webdriver/webdriver/lib/Remote/RemoteWebElement.php(345): Facebook\WebDriver\Remote\RemoteExecuteMethod->execute()


vendor/php-webdriver/webdriver/lib/Remote/RemoteExecuteMethod.php(27): Facebook\WebDriver\Remote\RemoteWebDriver->execute()

Call to a member function getBrowserName() on null in /home/forge/bigman.app/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:581
```

### How could the issue be reproduced

using Elgalu/Selenium

```php browser()->wait()->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id('withdrawal-pending-table')))```

**Comment by gwillyoo** [comment]
Yes, it is. I keep the browser session.

**Comment by OndraM** [comment]
Hi @gwillyoo, this is fixed in just released version 1.13.1.

Thanks for reporting this!

**Comment by y2wde** [comment]
> OndraM

I updated php-webdriver last week from 1.11.1 to 1.13.1 and I can confirm that wait-until now runs into an error, if the element not exists. 

For example:

```
$this->driver->wait(10, 500)->until(
 WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('shopping-cart-box'))
);
```

So this bug still exists and is not fixed with 1.13.1.
